### ISSUE TITLE
Please Just Help With the .lib

### ISSUE THREAD

**Issue by bassnbru** [Pocakking/BigBaseV2#2]
I know I already complained about myself being useless and not being able to fix the dependencies myself, but I literally can't find the libraries needed. @Pocakking **please** update the source. I will give you $0.90 ;).

**Comment by leapmotiondev** [comment]
https://github.com/TsudaKageyu/minhook
https://github.com/JochenKalmbach/StackWalker
done.

**Comment by bassnbru** [comment]
done? those be sources my dude. aint no .lib in sight

**Comment by leapmotiondev** [comment]
Huh? Tsuda has pushed some releases which include the libs and bins. If that doesn't help, download the source and compile the version you need. Rename it to MinHook.lib as Poca has set it so (or the other way around by changing the link option in visual studio itself) 

Jochen has described how to compile the libs with cmake. Nothing special. Just run those 3 commands and you get your libraries.

Just because this is a source for a ready2use imgui cheat, it doesn't mean you can lean back and let others even compile the libraries for you. Which is by far the easiest part other than downloading the source.

**Comment by bassnbru** [comment]
Oh thanks dude, and sorry I didn't mean this to come out as me being lazy, it was just me trying to learn and not fully understanding what was put in front of me. Anyways thanks dude, luv u know homo :)
